name: IONOS.space

on: [push]

jobs:
  ionos-space:
    runs-on: ubuntu-latest
    steps:
      - name: Get Ionos Project data
        uses: ionos-deploy-now/retrieve-project-info-action@v1
        id: project
        with:
          api-key: ${{ secrets.IONOS_API_KEY }}
          service-host: api-eu.ionos.space
          project: 971f22e9-707d-43eb-aa61-858a7e7a5875
      - name: checkout
        if: ${{ steps.project.outputs.deployment-enabled == 'true' }}
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - name: Setup Node.js 12.16.x
        if: ${{ steps.project.outputs.deployment-enabled == 'true' }}
        uses: actions/setup-node@v1
        with:
          node-version: 12.16.x
      - name: Prepare Project build environment
        if: ${{ steps.project.outputs.deployment-enabled == 'true' }}
        run: npm ci
      - name: Build Node project
        if: ${{ steps.project.outputs.deployment-enabled == 'true' }}
        run: npm run build
        env:
          SITE_URL: ${{ steps.project.outputs.site-url }}
          CI: true
      - name: Deploy to IONOS
        if: ${{ steps.project.outputs.deployment-enabled == 'true' }}
        uses: ionos-deploy-now/deploy-to-ionos-action@v1
        with:
          branch-id: ${{ steps.project.outputs.branch-id }}
          storage-quota: ${{ steps.project.outputs.storage-quota }}
          project: 971f22e9-707d-43eb-aa61-858a7e7a5875
          dist-folder: dist
          remote-host: ${{ steps.project.outputs.remote-host }}
          api-key: ${{ secrets.IONOS_API_KEY }}
          service-host: api-eu.ionos.space
